### ISSUE TITLE
Issue With Dicimals

### ISSUE THREAD

**Issue by mohamed-montaser1** [NdYAG/react-rater#79]
when i add dicimal number to the rating property dicimal number its just broke

```javascript
<Rater
  total={5}
  rating={2.5
}
  interactive={false}
  key={Math.random()}
>
```

![Screenshot 2024-05-26 042508](https://github.com/NdYAG/react-rater/assets/94475130/d7a55694-9ac2-41f5-b330-f9f47891a941)

i just need help ASAP as i'm working on a big project right now

**Comment by mohamed-montaser1** [comment]
I solved it.

the problem was in styling the before pseudo class.

it just make the ```css .react-rater-star.is-active-half``` relative and its before absolute with right of 0.

```css
.react-rater-star.is-active-half {
  @apply relative;
}

.react-rater-star.is-active-half::before {
  content: "\2605";
  @apply absolute right-0;
}
```

i hope this help somebody
